baseURL = "https://tasmant.github.io/"
title = "Killian Paul's Webpage"
theme = "PaperMod"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
  defaultTheme = "dark"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"
  [languages.fr]
    languageName = "Français"
    weight = 2
    contentDir = "content/fr"

[languages.en.menu]
  [[languages.en.menu.main]]
    name = "📚 Books"
    url = "/books/"
    weight = 1
  [[languages.en.menu.main]]
    name = "🎵 Music"
    url = "/music/"
    weight = 2
  [[languages.en.menu.main]]
    name = "🎮 Videogames"
    url = "/videogames/"
    weight = 3

[languages.fr.menu]
  [[languages.fr.menu.main]]
    name = "📚 Livres"
    url = "/fr/livres/"
    weight = 1
  [[languages.fr.menu.main]]
    name = "🎵 Musique"
    url = "/fr/musique/"
    weight = 2
  [[languages.fr.menu.main]]
    name = "🎮 Jeux vidéo"
    url = "/fr/jeuxvideo/"
    weight = 3
