baseURL = "https://tasmant.github.io/"
languageCode = "en"
title = "Killian Paul's Webpage"
theme = "PaperMod"

[params]
  defaultTheme = "dark"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.fr]
    languageName = "Français"
    weight = 2

[menu]
  [[languages.en.menu.main]]
    name = "📚 Books"
    url = "/en/books/"
    weight = 1
  [[languages.en.menu.main]]
    name = "🎵 Music"
    url = "/en/music/"
    weight = 2
  [[languages.en.menu.main]]
    name = "🎮 Videogames"
    url = "/en/videogames/"
    weight = 3
  [[languages.fr.menu.main]]
    name = "📚 Livres"
    url = "/fr/livres/"
    weight = 1
  [[languages.fr.menu.main]]
    name = "🎵 Musique"
    url = "/fr/musique/"
    weight = 2
  [[languages.fr.menu.main]]
    name = "🎮 Jeux vidéo"
    url = "/fr/jeuxvideo/"
    weight = 3
